master:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
        grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    hostName: jenkins.netw49fejp.nks.cloud
    tls:
    - secretName: wildcard-cert
      hosts:
      - jenkins.netw49fejp.nks.cloud
  prometheus:
    enabled: false
  installPlugins:
  - configuration-as-code:1.34
  - kubernetes:1.18.2
  - workflow-job:2.35
  - workflow-aggregator:2.6
  - credentials-binding:1.19
  - git:4.0.0
  - authorize-project:1.3.0
  - ldap:1.20
  - matrix-auth:2.5
  - blueocean:1.19.0
  - cloudbees-bitbucket-branch-source:2.6.0
  - artifactory:3.4.1
  - parameterized-trigger:2.35.2
  - ws-cleanup:0.37
  - slack:2.34
  - pipeline-utility-steps:2.3.1
  podAnnotations:
    linkerd.io/inject: enabled
  jobs:
    Demo: |-
      <?xml version='1.1' encoding='UTF-8'?>
      <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch@2.21">
        <actions/>
        <description></description>
        <displayName>Demo</displayName>
        <properties>
          <org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty plugin="kubernetes@1.18.2">
            <permittedClouds/>
          </org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty>
          <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.5.0">
            <dockerLabel></dockerLabel>
            <registry plugin="docker-commons@1.16"/>
          </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
        </properties>
        <folderViews class="jenkins.branch.MultiBranchProjectViewHolder" plugin="branch-api@2.5.5">
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </folderViews>
        <healthMetrics>
          <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.10.1">
            <nonRecursive>false</nonRecursive>
          </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
        </healthMetrics>
        <icon class="jenkins.branch.MetadataActionFolderIcon" plugin="branch-api@2.5.5">
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </icon>
        <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.10.1">
          <pruneDeadBranches>true</pruneDeadBranches>
          <daysToKeep>-1</daysToKeep>
          <numToKeep>-1</numToKeep>
        </orphanedItemStrategy>
        <triggers/>
        <disabled>false</disabled>
        <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@2.5.5">
          <data>
            <jenkins.branch.BranchSource>
              <source class="jenkins.plugins.git.GitSCMSource" plugin="git@4.0.0">
                <id>4b0be38c-276a-4e17-b7ee-67c63d0caa0d</id>
                <remote>https://github.com/sgryczan/nks-demo.git</remote>
                <credentialsId></credentialsId>
                <traits>
                  <jenkins.plugins.git.traits.BranchDiscoveryTrait/>
                </traits>
              </source>
              <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
                <properties class="empty-list"/>
              </strategy>
            </jenkins.branch.BranchSource>
          </data>
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </sources>
        <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory">
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
          <scriptPath>apps/website/Jenkinsfile</scriptPath>
        </factory>
      </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>
persistence:
  enabled: true