{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "website.serviceAccountName" . }}
  labels:
{{ include "website.labels" . | indent 4 }}
{{- end -}}
